sudo: required
services:
  - docker

before_install:
  - docker build -t agarwalaashish92/docker-react -f ./client/Dockerfile.dev ./c

script:
  -  docker run agarwalaashish92/docker-react npm test -- --coverage

after_sucess:
  -  docker build -t agarwalaashish92/multi-client ./client
  -  docker build -t agarwalaashish92/multi-nginx ./nginx
  -  docker build -t agarwalaashish92/multi-server ./server
  -  docker build -t agarwalaashish92/multi-worker ./worker

# Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin

# Take those images and push them to docker hub
  - docker push agarwalaashish92/multi-client
  - docker push agarwalaashish92/multi-nginx
  - docker push agarwalaashish92/multi-server
  - docker push agarwalaashish92/multi-worker