sudo: required
services:
  - docker

before_install:
  - docker build -t agarwalaashish92/docker-react -f ./client/Dockerfile.dev ./client

script:
  -  docker run agarwalaashish92/docker-react npm test -- --coverage

after_sucess:
  -  docker build -t agarwalaashish92/multi-client ./client
  -  docker build -t agarwalaashish92/multi-nginx ./nginx
  -  docker build -t agarwalaashish92/multi-server ./server
  -  docker build -t agarwalaashish92/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin

  - docker push agarwalaashish92/multi-client
  - docker push agarwalaashish92/multi-nginx
  - docker push agarwalaashish92/multi-server
  - docker push agarwalaashish92/multi-worker